# Generated by Django 6.0.2 on 2026-03-25 11:33

import django.core.validators
import django.db.models.deletion
import django_fsm
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsomeaPurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='po/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Finance créateur', limit_choices_to={'role': 'FINANCE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Client_PO_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, help_text='Référence unique Opportunity (ex: OPP-2024-00001)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nom descriptif du Opportunity', max_length=255)),
                ('status', django_fsm.FSMField(choices=[('DRAFT', 'Brouillon'), ('SUPPLIER_QUOTE_REQUEST', 'Devis fournisseur demandé'), ('SUPPLIER_QUOTE_RECIEVED', 'Devis fournisseur reçu'), ('INSOMEA_QUOTE_CREATED', 'Devis Insomea créé'), ('CLIENT_PO_REQUEST', 'BC client demandé'), ('CLIENT_PO_RECIEVED', 'BC client reçu'), ('APPROUVED', 'approuvée'), ('CANCELLED', 'Annulé')], db_index=True, default='DRAFT', max_length=50)),
                ('type', models.CharField(choices=[('INITIAL', 'Vente initiale'), ('RENEWAL', 'Renouvellement'), ('UPSELL', 'Vente additionnelle'), ('DOWNGRADE', 'Réduction')], default='INITIAL', help_text='Type opportunité', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes internes')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Raison annulation')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Utilisateur assigné (responsable actuel)', limit_choices_to={'role__in': ['COMMERCIAL', 'TECHNICIEN', 'FINANCE']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Opportunities_assigned', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='Client concerné', on_delete=django.db.models.deletion.PROTECT, related_name='Opportunities', to='clients.client')),
                ('created_by', models.ForeignKey(help_text='Commercial créateur', limit_choices_to={'role': 'COMMERCIAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Opportunities_created', to=settings.AUTH_USER_MODEL)),
                ('related_opportunity', models.ForeignKey(blank=True, help_text='Opportunité parente (si renewal/upsell/downgrade)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_opportunities', to='ventes.opportunity')),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'db_table': 'Opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsomeaQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, help_text='Référence unique InsomeaQuote (ex: INSOMEA-2024-00001)', max_length=50, unique=True)),
                ('document', models.FileField(upload_to='quotes/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('subtotal_purchase', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sous-total achat', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_purchase', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total achat', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal_sale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sous-total vente', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_sale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total vente', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant remise', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remise globale en %', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Marge totale', max_digits=12)),
                ('margin_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Marge %', max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, help_text='Commercial créateur', limit_choices_to={'role': 'COMMERCIAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Insomea_quote_created', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insomea_quote', to='ventes.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='po/')),
                ('recieved_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(help_text='Commercial créateur', limit_choices_to={'role': 'COMMERCIAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Client_po_created', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_purchase_order', to='ventes.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Mensuel'), ('ANNUAL', 'Annuel')], default='ANNUAL', help_text='Cycle de facturation', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantité de licences', validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True, help_text='Notes spécifiques ligne')),
                ('status', django_fsm.FSMField(choices=[('DRAFT', 'Brouillon'), ('SUPPLIER_QUOTE_REQUEST', 'Devis fournisseur demandé'), ('SUPPLIER_QUOTE_RECIEVED', 'Devis fournisseur reçu'), ('CANCELLED', 'Annulé')], db_index=True, default='DRAFT', help_text='Statut FSM de la ligne', max_length=50, protected=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insomea_purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Insomea_purchase_order', to='ventes.insomeapurchaseorder')),
                ('opportunity', models.ForeignKey(help_text='Opportunity parent', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ventes.opportunity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'verbose_name': 'Opportunity line',
                'verbose_name_plural': 'Opportunity lines',
                'db_table': 'Opportunity_Lines',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Provision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('microsoft_subscription_id', models.CharField(blank=True, help_text='Subscription ID Microsoft', max_length=255)),
                ('provisioning_started_at', models.DateTimeField(blank=True, help_text='Date début provisionnement', null=True)),
                ('provisioning_completed_at', models.DateTimeField(blank=True, help_text='Date fin provisionnement', null=True)),
                ('provisioning_error', models.TextField(blank=True, help_text='Erreur provisionnement (si échec)')),
                ('status', django_fsm.FSMField(choices=[('WAITING_PROVISION', 'À approvisionner'), ('PROVISIONING', 'En cours approvisionnement'), ('PROVISIONED', 'Terminé'), ('ERROR', 'erreur')], db_index=True, default='WAITING_PROVISION', max_length=50, protected=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='provision', to='ventes.opportunityline')),
                ('provisionned_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'TECHNICIEN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provision',
                'verbose_name_plural': 'Provisions',
                'db_table': 'provisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_number', models.CharField(max_length=100)),
                ('current_term_start', models.DateField()),
                ('current_term_end', models.DateField()),
                ('quantity', models.PositiveIntegerField(help_text='Quantité licences', validators=[django.core.validators.MinValueValidator(1)])),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Mensuel'), ('ANNUAL', 'Annuel')], help_text='Cycle de facturation', max_length=20)),
                ('auto_renew', models.BooleanField(default=True, help_text='Renouvellement automatique activé')),
                ('status', django_fsm.FSMField(choices=[('ACTIVE', 'Active'), ('PENDING_RENEWAL', 'En attente renouvellement'), ('EXPIRED', 'Expirée'), ('CANCELLED', 'Annulée')], default='ACTIVE', max_length=50, protected=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client propriétaire', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='clients.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='products.product')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_precedent', models.CharField(help_text='Statut AVANT transition', max_length=50)),
                ('status_suivant', models.CharField(help_text='Statut APRÈS transition', max_length=50)),
                ('transition_name', models.CharField(blank=True, help_text="Nom de la transition FSM (ex: 'request_supplier_quote')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description détaillée du changement')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données additionnelles (JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'utilisateur", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date/heure du changement')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Utilisateur ayant effectué le changement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(blank=True, help_text='Opportunité (si transition Opportunity FSM)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ventes.opportunity')),
                ('opportunity_line', models.ForeignKey(blank=True, help_text='Ligne (si transition OpportunityLine FSM)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ventes.opportunityline')),
                ('provision', models.ForeignKey(blank=True, help_text='Provision (si transition Provision FSM)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ventes.provision')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ventes.subscription')),
            ],
            options={
                'verbose_name': 'Historique statut',
                'verbose_name_plural': 'Historiques statuts',
                'db_table': 'status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='provision',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='ventes.subscription'),
        ),
        migrations.AddField(
            model_name='opportunityline',
            name='renewal_of_subscription',
            field=models.ForeignKey(blank=True, help_text='Subscription renouvelée (si Opportunity.type=RENEWAL)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_lines', to='ventes.subscription'),
        ),
        migrations.CreateModel(
            name='SubscriptionTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('unit_price_purchase', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unit_price_sale', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_purchase', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_sale', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('auto_renew_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(help_text='Opportunité ayant généré ce terme (INITIAL ou RENEWAL)', on_delete=django.db.models.deletion.PROTECT, related_name='subscription_terms', to='ventes.opportunity')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='ventes.subscription')),
            ],
            options={
                'verbose_name': 'Terme subscription',
                'verbose_name_plural': 'Termes subscriptions',
                'db_table': 'subscription_terms',
                'ordering': ['subscription', 'term_number'],
            },
        ),
        migrations.AddField(
            model_name='provision',
            name='subscription_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provision', to='ventes.subscriptionterm'),
        ),
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, help_text='Référence unique SupplierQuote', max_length=50, unique=True)),
                ('document', models.FileField(upload_to='')),
                ('recieved_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('subtotal_purchase', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sous-total achat', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_purchase', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total achat', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant remise', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remise globale en %', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('created_by', models.ForeignKey(help_text='Commercial créateur', limit_choices_to={'role': 'COMMERCIAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Supplier_quote_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierQuoteLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price_purchase', models.DecimalField(decimal_places=2, help_text='Prix unitaire achat', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('line_total_purchase', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total achat calculé', max_digits=12)),
                ('currency', models.CharField(max_length=10)),
                ('delivery_time', models.IntegerField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('opportunity_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_quote_line', to='ventes.opportunityline')),
                ('supplier_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ventes.supplierquote')),
            ],
        ),
        migrations.CreateModel(
            name='InsomeaQuoteLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price_purchase', models.DecimalField(decimal_places=2, help_text='Prix unitaire achat', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('line_total_purchase', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total achat calculé', max_digits=12)),
                ('unit_price_sale', models.DecimalField(decimal_places=2, help_text='Prix unitaire vente', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('line_total_sale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total vente calculé', max_digits=12)),
                ('line_margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('insomea_quote', models.ForeignKey(help_text='InsomeaQuote parent', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ventes.insomeaquote')),
                ('opportunity_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insomea_quote_line', to='ventes.opportunityline')),
                ('supplier_quote_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insomea_quote_line', to='ventes.supplierquoteline')),
            ],
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['reference'], name='Opportuniti_referen_981206_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['client', 'status'], name='Opportuniti_client__7a6dce_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['created_by', 'status'], name='Opportuniti_created_0f607f_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['assigned_to', 'status'], name='Opportuniti_assigne_fb9450_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['status', 'created_at'], name='Opportuniti_status_1b187e_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['type', 'created_at'], name='Opportuniti_type_f2cad5_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['related_opportunity'], name='Opportuniti_related_5c8353_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['subscription_number'], name='subscriptio_subscri_c6349d_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['client', 'status'], name='subscriptio_client__e90ac2_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['product', 'status'], name='subscriptio_product_5bacd0_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['current_term_end', 'status'], name='subscriptio_current_59e276_idx'),
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['opportunity', '-created_at'], name='status_hist_opportu_24c026_idx'),
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['opportunity_line', '-created_at'], name='status_hist_opportu_bf0e73_idx'),
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['provision', '-created_at'], name='status_hist_provisi_991cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['created_at'], name='status_hist_created_f5bb05_idx'),
        ),
        migrations.AddConstraint(
            model_name='statushistory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('opportunity__isnull', False), ('opportunity_line__isnull', True), ('provision__isnull', True)), models.Q(('opportunity__isnull', True), ('opportunity_line__isnull', False), ('provision__isnull', True)), models.Q(('opportunity__isnull', True), ('opportunity_line__isnull', True), ('provision__isnull', False)), _connector='OR'), name='only_one_entity_must_be_set'),
        ),
        migrations.AddIndex(
            model_name='opportunityline',
            index=models.Index(fields=['opportunity', 'status'], name='Opportunity_opportu_024779_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunityline',
            constraint=models.UniqueConstraint(fields=('opportunity', 'product'), name='unique_product_per_Opportunity'),
        ),
        migrations.AddIndex(
            model_name='subscriptionterm',
            index=models.Index(fields=['subscription', 'term_number'], name='subscriptio_subscri_881d43_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionterm',
            index=models.Index(fields=['start_date', 'end_date'], name='subscriptio_start_d_a908b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionterm',
            constraint=models.UniqueConstraint(fields=('subscription', 'term_number'), name='unique_subscription_term_number'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionterm',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='term_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='provision',
            index=models.Index(fields=['status', 'created_at'], name='provisions_status_44d6a3_idx'),
        ),
        migrations.AddIndex(
            model_name='provision',
            index=models.Index(fields=['provisionned_by', 'status'], name='provisions_provisi_fe6663_idx'),
        ),
        migrations.AddIndex(
            model_name='provision',
            index=models.Index(fields=['opportunity_line'], name='provisions_opportu_41af4b_idx'),
        ),
        migrations.AddIndex(
            model_name='provision',
            index=models.Index(fields=['subscription'], name='provisions_subscri_52c6f6_idx'),
        ),
    ]
