# Generated by Django 6.0.2 on 2026-04-07 10:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='insomeaquote',
            name='document',
            field=models.FileField(blank=True, upload_to='quotes/client/'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FINANCE_APPROVE', 'Finance: Approuver opportunité'), ('TECH_PROVISION_WAITING', 'Tech: Provision en attente'), ('SUBSCRIPTION_PROVISIONED', 'Subscription provisionnée'), ('SUBSCRIPTION_EXPIRING', 'Subscription expire bientôt'), ('SUBSCRIPTION_EXPIRED', 'Subscription expirée')], help_text='Type notification', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, help_text='URL action (ex: /opportunities/123/)', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyée'), ('READ', 'Lue'), ('FAILED', 'Échec')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='ventes.opportunity')),
                ('provision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='ventes.provision')),
                ('recipient', models.ForeignKey(help_text='Destinataire', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='ventes.subscription')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status', '-created_at'], name='notificatio_recipie_20131c_idx'), models.Index(fields=['type', '-created_at'], name='notificatio_type_d2e2f1_idx')],
            },
        ),
    ]
