# Generated by Django 6.0.2 on 2026-03-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='statushistory',
            name='status_hist_opportu_24c026_idx',
        ),
        migrations.RemoveIndex(
            model_name='statushistory',
            name='status_hist_opportu_bf0e73_idx',
        ),
        migrations.RemoveIndex(
            model_name='statushistory',
            name='status_hist_provisi_991cf4_idx',
        ),
        migrations.RemoveIndex(
            model_name='statushistory',
            name='status_hist_created_f5bb05_idx',
        ),
        migrations.RemoveConstraint(
            model_name='statushistory',
            name='only_one_entity_must_be_set',
        ),
        migrations.DeleteModel(
            name='StatusHistory',
        ),
    ]
