# Generated by Django 6.0.2 on 2026-03-26 13:21

import apps.ventes.models.clientPurchaseOder
import apps.ventes.models.insomeaPurchaseOrder
import apps.ventes.models.insomeaQuote
import apps.ventes.models.supplierQuote
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('ventes', '0002_remove_statushistory_status_hist_opportu_24c026_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpo',
            name='document',
            field=models.FileField(upload_to=apps.ventes.models.clientPurchaseOder.get_upload_path),
        ),
        migrations.AlterField(
            model_name='insomeapurchaseorder',
            name='document',
            field=models.FileField(upload_to=apps.ventes.models.insomeaPurchaseOrder.get_upload_path),
        ),
        migrations.AlterField(
            model_name='insomeaquote',
            name='document',
            field=models.FileField(upload_to=apps.ventes.models.insomeaQuote.get_upload_path),
        ),
        migrations.AlterField(
            model_name='supplierquote',
            name='document',
            field=models.FileField(upload_to=apps.ventes.models.supplierQuote.get_upload_path),
        ),
        migrations.AddIndex(
            model_name='insomeaquote',
            index=models.Index(fields=['opportunity', 'created_at'], name='ventes_inso_opportu_8a5cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='insomeaquote',
            index=models.Index(fields=['reference'], name='ventes_inso_referen_157323_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierquote',
            index=models.Index(fields=['reference'], name='ventes_supp_referen_4fdadc_idx'),
        ),
    ]
