# Generated by Django 6.0.2 on 2026-04-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_alter_insomeaquote_document_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='provision',
            name='is_renewal',
            field=models.BooleanField(default=False, help_text="True si renewal d'une subscription existante, False si initial"),
        ),
    ]
