# Generated by Django 6.0.2 on 2026-03-30 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_alter_clientpo_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur Finance ayant approuvé cette opportunité', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provision',
            name='subscription_term',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provision', to='ventes.subscriptionterm'),
        ),
    ]
