# Generated by Django 6.0.2 on 2026-04-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0005_subscription_notified_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('FINANCE_APPROVE', 'Finance: Approuver opportunité'), ('TECH_PROVISION_WAITING', 'Tech: Provision en attente'), ('SUBSCRIPTION_PROVISIONED', 'Subscription provisionnée'), ('SUBSCRIPTION_EXPIRING', 'Subscription expire bientôt'), ('SUBSCRIPTION_EXPIRED', 'Subscription expirée'), ('EMAIL_FAILED', 'Échec envoi email')], help_text='Type notification', max_length=50),
        ),
    ]
