# Generated by Django 6.0.2 on 2026-04-23 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0006_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpo',
            name='created_by',
            field=models.ForeignKey(help_text='Commercial créateur', limit_choices_to={'role_id': 'COMMERCIAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Client_po_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insomeapurchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Finance créateur', limit_choices_to={'role_id': 'FINANCE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insomea_pos_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insomeaquote',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Commercial créateur', limit_choices_to={'role_id': 'COMMERCIAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Insomea_quote_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Utilisateur assigné (responsable actuel)', limit_choices_to={'role_id__in': ['COMMERCIAL', 'TECHNICIEN', 'FINANCE']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Opportunities_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='created_by',
            field=models.ForeignKey(help_text='Commercial créateur', limit_choices_to={'role_id': 'COMMERCIAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Opportunities_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provision',
            name='provisionned_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role_id': 'TECHNICIEN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplierquote',
            name='created_by',
            field=models.ForeignKey(help_text='Commercial créateur', limit_choices_to={'role_id': 'COMMERCIAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Supplier_quote_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
