# Generated by Django 6.0.2 on 2026-05-06 12:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0007_alter_clientpo_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_precedent', models.CharField(blank=True, help_text='Statut AVANT transition', max_length=50)),
                ('status_suivant', models.CharField(help_text='Statut APRÈS transition', max_length=50)),
                ('transition_name', models.CharField(blank=True, help_text='Nom de la transition FSM', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description détaillée du changement')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données additionnelles (JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'utilisateur", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date/heure du changement')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Utilisateur ayant effectué le changement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(blank=True, help_text='Opportunité (si transition Opportunity FSM)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ventes.opportunity')),
                ('opportunity_line', models.ForeignKey(blank=True, help_text='Ligne (si transition OpportunityLine FSM)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ventes.opportunityline')),
                ('provision', models.ForeignKey(blank=True, help_text='Provision (si transition Provision FSM)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ventes.provision')),
                ('subscription', models.ForeignKey(blank=True, help_text='Subscription (si transition Subscription FSM)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ventes.subscription')),
            ],
            options={
                'verbose_name': 'Historique statut',
                'verbose_name_plural': 'Historiques statuts',
                'db_table': 'status_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['opportunity', '-created_at'], name='status_hist_opportu_24c026_idx'), models.Index(fields=['opportunity_line', '-created_at'], name='status_hist_opportu_bf0e73_idx'), models.Index(fields=['provision', '-created_at'], name='status_hist_provisi_991cf4_idx'), models.Index(fields=['subscription', '-created_at'], name='status_hist_subscri_082f17_idx'), models.Index(fields=['created_at'], name='status_hist_created_f5bb05_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('opportunity__isnull', False), ('opportunity_line__isnull', True), ('provision__isnull', True), ('subscription__isnull', True)), models.Q(('opportunity__isnull', True), ('opportunity_line__isnull', False), ('provision__isnull', True), ('subscription__isnull', True)), models.Q(('opportunity__isnull', True), ('opportunity_line__isnull', True), ('provision__isnull', False), ('subscription__isnull', True)), models.Q(('opportunity__isnull', True), ('opportunity_line__isnull', True), ('provision__isnull', True), ('subscription__isnull', False)), _connector='OR'), name='status_history_only_one_entity_set')],
            },
        ),
    ]
