# Generated by Django 6.0.2 on 2026-05-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0008_add_status_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('FINANCE_APPROVE', 'Finance: Approuver opportunité'), ('TECH_PROVISION_WAITING', 'Tech: Provision en attente'), ('SUBSCRIPTION_PROVISIONED', 'Subscription provisionnée'), ('SUBSCRIPTION_EXPIRING', 'Subscription expire bientôt'), ('SUBSCRIPTION_EXPIRED', 'Subscription expirée'), ('EMAIL_FAILED', 'Échec envoi email'), ('NOUVEAU_LEAD', 'Nouvelle demande client')], help_text='Type notification', max_length=50),
        ),
    ]
