"""
Django settings for insomea_crm project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
from datetime import timedelta
from celery.schedules import crontab


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


#redis
"""
# ═══════════════════════════════════════════════════════════
# SECURITY SETTINGS
# ═══════════════════════════════════════════════════════════

SECRET_KEY = config('SECRET_KEY')
# Explication : Clé secrète pour signer les JWT et cookies
# DOIT être longue et aléatoire en production
# Générer avec : python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"

DEBUG = config('DEBUG', default=False, cast=bool)
# Explication : DEBUG=False en production pour ne pas exposer les erreurs

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')
# Explication : Liste des domaines autorisés
# En production : ['app.insomea.tn', 'www.insomea.tn']

# Security Headers (PRODUCTION)
SECURE_SSL_REDIRECT = not DEBUG  
# Explication : Force HTTPS en production
# Si user va sur http://app.com → redirige vers https://app.com

SESSION_COOKIE_SECURE = not DEBUG
# Explication : Les cookies de session ne sont envoyés que via HTTPS

CSRF_COOKIE_SECURE = not DEBUG
# Explication : Les cookies CSRF ne sont envoyés que via HTTPS

SECURE_BROWSER_XSS_FILTER = True
# Explication : Active le filtre XSS du navigateur

SECURE_CONTENT_TYPE_NOSNIFF = True
# Explication : Empêche le browser de "deviner" le content-type

X_FRAME_OPTIONS = 'DENY'
# Explication : Empêche le site d'être affiché dans une <iframe>
# Protection contre clickjacking

SECURE_HSTS_SECONDS = 31536000  # 1 an
# Explication : Force HTTPS pendant 1 an (HTTP Strict Transport Security)

SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# Explication : HSTS s'applique aussi aux sous-domaines
"""




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_%r@od*(f2&gr!@hpqhcvhcug4p=3sma893#i@hm=b(s8bf+61'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # for logout
    'corsheaders',
    'django_filters',
    'drf_spectacular',
    'channels',
    'celery',
    'django_celery_beat',
    "django_celery_results",
    
    # Local apps
    'apps.users.apps.UsersConfig',
    'apps.authentication.apps.AuthenticationConfig',
    'apps.clients.apps.ClientsConfig',
    'apps.products.apps.ProductsConfig',
    'apps.suppliers.apps.SuppliersConfig',
    'apps.ventes.apps.VentesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware', #CORS
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'config.asgi.application'

# ═══════════════════════════════════════════════════════════
# CHANNELS CONFIGURATION
# ═══════════════════════════════════════════════════════════

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [config('REDIS_URL', default='redis://localhost:6379/0')],
        },
    },
}

# ═══════════════════════════════════════════════════════════
# CORS (pour WebSocket connections)
# ═══════════════════════════════════════════════════════════

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React dev
    "http://localhost:5173",  # Vite dev
    config('FRONTEND_URL', default='http://localhost:3000'),
]

CORS_ALLOW_CREDENTIALS = True


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='insomea_crm'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='postgres'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # 100 requêtes/heure pour utilisateurs non-authentifiés
        'user': '1000/hour', # 1000 requêtes/heure pour utilisateurs authentifiés
        'login': '5/15min',  # 5 tentatives de login par 15 minutes (brute-force protection)
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),  # Token valide 24h
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),   # Refresh token valide 7 jours
    'ROTATE_REFRESH_TOKENS': True,                 # Nouveau refresh token à chaque refresh
    'BLACKLIST_AFTER_ROTATION': True,              # Blacklist l'ancien token
    'UPDATE_LAST_LOGIN': True,                     # Met à jour last_login
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    'JTI_CLAIM': 'jti',

    'AUTH_COOKIE': 'access_token',
    'AUTH_COOKIE_REFRESH': 'refresh_token',
    'AUTH_COOKIE_SECURE': not DEBUG,  # HTTPS only en production
    'AUTH_COOKIE_HTTP_ONLY': True,
    # Explication : HTTP-only empêche JavaScript d'accéder au cookie
    # Protection contre XSS
    
    'AUTH_COOKIE_SAMESITE': 'Lax',
    # Explication : Protection CSRF (Lax = cookies envoyés avec top-level navigation)
}


# CORS Configuration
CORS_ALLOWED_ORIGINS = config(
    'CORS_ORIGINS', 
    default='http://localhost:5173,http://localhost:3000'
).split(',')

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
# Explication : Utilise SMTP pour envoyer emails réels
# En dev, on peut utiliser 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
# Explication : Serveur SMTP (Gmail, SendGrid, etc.)

EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
# Explication : Port SMTP (587 = TLS, 465 = SSL)

EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True)
# Explication : Utilise TLS pour chiffrer emails

EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
# Explication : Email expéditeur (ex: noreply@insomea.tn)

EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
# Explication : Password ou App Password de l'email

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@insomea.tn')
# Explication : Email affiché comme expéditeur

# Email addresses teams
FINANCE_TEAM_EMAIL = config('FINANCE_TEAM_EMAIL', default='finance@insomea.com')
TECH_TEAM_EMAIL = config('TECH_TEAM_EMAIL', default='tech@insomea.com')
ADMIN_EMAIL = config('ADMIN_EMAIL', default='admin@insomea.com')

# ═══════════════════════════════════════════════════════════
# FRONTEND URL (pour les liens dans emails)
# ═══════════════════════════════════════════════════════════

FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:5173')
# Explication : URL du frontend React
# Utilisé pour générer les liens de setup et reset password
# Ex: https://app.insomea.tn/setup?token=abc123

# ═══════════════════════════════════════════════════════════
# SETUP TOKEN CONFIGURATION
# ═══════════════════════════════════════════════════════════

SETUP_TOKEN_EXPIRY_HOURS = 24
# Explication : Token de setup expire après 24 heures

PASSWORD_RESET_TOKEN_EXPIRY_HOURS = 1
# Explication : Token de reset password expire après 1 heure (plus court = plus sécurisé)

# ═══════════════════════════════════════════════════════════
# RATE LIMITING (django-ratelimit)
# ═══════════════════════════════════════════════════════════

#RATELIMIT_ENABLE = not DEBUG
# Explication : Active rate limiting en production seulement

RATELIMIT_USE_CACHE = 'default'
# Explication : Utilise le cache Django pour stocker les compteurs

# Cache Configuration (Redis recommandé pour production)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        # En production, utiliser Redis :
        # 'BACKEND': 'django_redis.cache.RedisCache',
        # 'LOCATION': config('REDIS_URL', default='redis://127.0.0.1:6379/1'),
    }
}


















# ... (autres settings existants)

# ═══════════════════════════════════════════════════════════
# CELERY CONFIGURATION
# ═══════════════════════════════════════════════════════════

CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Celery Beat Schedule (cron jobs)
CELERY_BEAT_SCHEDULE = {
    # Vérifie subscriptions expirant (daily 8am UTC)
    'check-expiring-subscriptions': {
        'task': 'opportunities.tasks.check_expiring_subscriptions',
        'schedule': crontab(hour=8, minute=0),  # 8:00 AM UTC daily
    },
    
    # Expire subscriptions non renouvelées (daily 9am UTC)
    'expire-unrenewed-subscriptions': {
        'task': 'opportunities.tasks.expire_unrenewed_subscriptions',
        'schedule': crontab(hour=9, minute=0),  # 9:00 AM UTC daily
    },
}


SPECTACULAR_SETTINGS = {
    'TITLE': 'InsomeaCRM API',
    'DESCRIPTION': 'a custom web application designed to automate the licensing lifecycle management',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}