# Generated by Django 6.0.2 on 2026-03-31 17:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(db_index=True, help_text='SKU Microsoft (ex: CFQ7TTC0LH18:0001)', max_length=100, unique=True)),
                ('title', models.CharField(db_index=True, help_text='Nom commercial du produit', max_length=255)),
                ('category', models.CharField(choices=[('OFFICE_365', 'Office 365'), ('MICROSOFT_365', 'Microsoft 365'), ('WINDOWS', 'Windows'), ('AZURE', 'Azure'), ('DYNAMICS', 'Dynamics 365'), ('POWER_PLATFORM', 'Power Platform'), ('SECURITY', 'Sécurité'), ('OTHER', 'Autre')], db_index=True, default='OTHER', max_length=50)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('publisher', models.CharField(db_index=True, max_length=255)),
                ('description_technique', models.TextField(blank=True, help_text='Description technique détaillée')),
                ('description_commerciale', models.TextField(blank=True, help_text='Description commerciale pour clients')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Produit actif dans le catalogue ?')),
                ('is_deprecated', models.BooleanField(db_index=True, default=False, help_text='Produit obsolète/déprécié ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('successor', models.ForeignKey(blank=True, help_text='Produit remplaçant (si obsolète)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecessors', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'products',
                'ordering': ['title', 'version'],
                'indexes': [models.Index(fields=['sku'], name='products_sku_fe2039_idx'), models.Index(fields=['title'], name='products_title_6a4e5e_idx'), models.Index(fields=['category', 'is_active'], name='products_categor_417272_idx'), models.Index(fields=['supplier', 'is_active'], name='products_supplie_838d93_idx')],
            },
        ),
    ]
