# Generated by Django 6.0.2 on 2026-03-09 13:46

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Adresse email')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('COMMERCIAL', 'Commercial'), ('TECHNICIEN', 'Technicien'), ('FINANCE', 'Finance')], default='COMMERCIAL', max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateurs',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='utilisateur_email_1cb90f_idx'), models.Index(fields=['role'], name='utilisateur_role_56bb83_idx'), models.Index(fields=['is_active'], name='utilisateur_is_acti_833ede_idx')],
            },
        ),
    ]
