# Generated by Django 6.0.2 on 2026-03-30 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(db_index=True, help_text="Identifiant machine (ex: 'opportunity.create')", max_length=100, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text="Label lisible (ex: 'Créer une opportunité')", max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, help_text='Contexte optionnel sur ce que cette permission autorise', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'rbac_permissions',
                'ordering': ['codename'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('COMMERCIAL', 'Commercial'), ('TECHNICIEN', 'Technicien'), ('FINANCE', 'Finance')], db_index=True, max_length=20, verbose_name='Rôle')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.permission', verbose_name='Permission')),
            ],
            options={
                'verbose_name': 'Permission par rôle',
                'verbose_name_plural': 'Permissions par rôle',
                'db_table': 'rbac_role_permissions',
                'indexes': [models.Index(fields=['role'], name='rbac_role_p_role_2ac3e5_idx')],
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
