# Generated by Django 6.0.2 on 2026-04-23 14:52

import django.db.models.deletion
from django.db import migrations, models


def seed_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    for name, display_name in [
        ('ADMIN', 'Administrateur'),
        ('COMMERCIAL', 'Commercial'),
        ('TECHNICIEN', 'Technicien'),
        ('FINANCE', 'Finance'),
    ]:
        Role.objects.get_or_create(name=name, defaults={'display_name': display_name})


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Nom')),
                ('display_name', models.CharField(max_length=100, verbose_name='Nom affiché')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'db_table': 'rbac_roles',
                'ordering': ['name'],
            },
        ),
        # Seed role rows BEFORE adding FK constraints so existing data stays valid
        migrations.RunPython(seed_roles, reverse_code=migrations.RunPython.noop),
        migrations.RenameIndex(
            model_name='rolepermission',
            new_name='rbac_role_p_role_na_79d6c6_idx',
            old_name='rbac_role_p_role_2ac3e5_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='utilisateur_role_na_1d7a12_idx',
            old_name='utilisateur_role_56bb83_idx',
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(db_column='role_name', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.role', to_field='name', verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(db_column='role_name', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.role', to_field='name', verbose_name='Rôle'),
        ),
    ]
