# Generated by Django 6.0.2 on 2026-05-18 18:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventes', '0009_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_entreprise', models.CharField(max_length=200)),
                ('nom_contact', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('produits_suggeres', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('PRISE_EN_CHARGE', 'Prise en charge'), ('CONVERTIE', 'Convertie'), ('ANNULEE', 'Annulée')], default='NOUVELLE', max_length=20)),
                ('prise_en_charge_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_source', to='ventes.opportunity')),
                ('prise_en_charge_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_prises_en_charge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande client',
                'verbose_name_plural': 'Demandes clients',
                'db_table': 'leads_demandes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['statut', '-created_at'], name='leads_deman_statut_0a1fd9_idx'), models.Index(fields=['prise_en_charge_par', 'statut'], name='leads_deman_prise_e_d09e85_idx')],
            },
        ),
    ]
