# Generated by Django 6.0.2 on 2026-03-31 17:02

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('type', models.CharField(choices=[('DIRECT', 'Direct (Microsoft)'), ('DISTRIBUTOR', 'Distributeur'), ('RESELLER', 'Revendeur')], db_index=True, default='DISTRIBUTOR', max_length=20)),
                ('website', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'db_table': 'suppliers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='suppliers_name_ed482a_idx'), models.Index(fields=['type', 'is_active'], name='suppliers_type_5e3d17_idx')],
            },
        ),
    ]
