# Generated by Django 6.0.2 on 2026-03-31 17:02

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_index=True, max_length=255, verbose_name='Raison sociale')),
                ('registration_number', models.CharField(blank=True, help_text='Numéro de registre de commerce ou équivalent', max_length=100, null=True, verbose_name="Numéro d'enregistrement")),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Matricule fiscale')),
                ('industry', models.CharField(choices=[('IT', "Technologies de l'information"), ('TELECOM', 'Télécommunications'), ('FINANCE', 'Finance et banque'), ('MANUFACTURING', 'Industrie manufacturière'), ('RETAIL', 'Commerce et distribution'), ('HEALTHCARE', 'Santé'), ('EDUCATION', 'Éducation'), ('GOVERNMENT', 'Secteur public'), ('ENERGY', 'Énergie'), ('AGRICULTURE', 'Agriculture'), ('TOURISM', 'Tourisme et hôtellerie'), ('TRANSPORT', 'Transport et logistique'), ('OTHER', 'Autre')], db_index=True, default='OTHER', max_length=50, verbose_name="Secteur d'activité")),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email principal')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('website', models.URLField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='Site web')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Gouvernorat')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(db_index=True, default='Tunisie', max_length=100, verbose_name='Pays')),
                ('status', models.CharField(choices=[('LEAD', 'Lead'), ('PROSPECT', 'Prospect'), ('CUSTOMER', 'Client'), ('INACTIVE', 'Inactif')], db_index=True, default='LEAD', max_length=20, verbose_name='Statut')),
                ('tenant_microsoft', models.CharField(blank=True, help_text='Tenant ID Microsoft 365 pour provisioning', max_length=255, verbose_name='Tenant Microsoft')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nom')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Poste')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Mobile')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Contact principal')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
                'ordering': ['-is_primary', 'last_name', 'first_name'],
            },
        ),
    ]
