# Generated by Django 6.0.2 on 2026-03-31 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'COMMERCIAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status', 'is_active'], name='idx_client_status_active'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['assigned_to', 'is_active'], name='idx_client_assigned_active'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at'], name='idx_client_created'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('email',), name='unique_active_client_email'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['client', 'is_primary'], name='idx_contact_client_primary'),
        ),
    ]
