# Generated by Django 6.0.2 on 2026-04-02 15:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('CREATED', 'Créé'), ('UPDATED', 'Modifié'), ('DELETED', 'Désactivé'), ('RESTORED', 'Réactivé'), ('ASSIGNED', 'Réassigné')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'client_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='idx_client_status_active',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='client',
            name='tenant_microsoft',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tenant Microsoft'),
        ),
        migrations.AddField(
            model_name='clientactivity',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='clients.client'),
        ),
        migrations.AddField(
            model_name='clientactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.RemoveField(
            model_name='client',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='state',
        ),
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tax_id',
        ),
    ]
